FROM ghcr.io/compbiocore/dennery_singlecell_reanalysis:may_07_09-36-02_2024
#RUN R -e 'install.packages("devtools")'
RUN R -e 'devtools::install_github("cole-trapnell-lab/leidenbase")' 
#RUN R -e 'devtools::install_github("cole-trapnell-lab/monocle3")' 
